### ISSUE TITLE
Synchronize the latest index from the leader node

### ISSUE THREAD

**Issue by mosuka** [mosuka/cockatrice#21]
Synchronize the latest index from the leader node if the follower node does not have the latest index in start up.

**Comment by bakwc** [comment]
You need to write custom serialize and deserialize function and pass it to SyncObjConf. Here is an example of serialization / deserealization of the external state:
https://github.com/bakwc/DbSyncer/blob/master/firebird_driver.py#L25
https://github.com/bakwc/DbSyncer/blob/master/dbsyncer.py

**Comment by mosuka** [comment]
done.
